[package]
name = "album_img"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

notify = "4.0.17"
ctrlc = "3.2.4"

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["image"]
